### ISSUE TITLE
MYSQLoo

### ISSUE THREAD

**Issue by Heyter** [DeadiKation/raindrop#16]
Does not create a table in mysql
Module: Mysqloo v9
Using: freemysqlhosting.net

**Comment by SellMG** [comment]
When nobody reply an issue T_T

**Comment by Heyter** [comment]
Project dead maybe.

**Comment by DeadiKation** [comment]
@Heyter @Johnny7A2 I believe Johnny coded it to only use TMySQL4. Never got around to using MySQLoo. But Unless someone else comes in and fixes or updates the SQL it's bound to stay that way.

**Comment by Heyter** [comment]
Mysloo v9 faster than TMysql4.

**Comment by Heyter** [comment]
@DeadiKation, Mysloo v9 faster than TMysql4.

**Comment by DeadiKation** [comment]
I understand it's faster, and asked if it could be written for it. However he never got around to adding it. Thus unless a coder adds it, it is as is.

**Comment by Heyter** [comment]
@DeadiKation, This is bad.

**Comment by BeZerkFP** [comment]
You guys need to learn to read and understand that this project badly needs coders to finish it, rather than complaining why don't YOU fix it and push the fix here.

**Comment by Heyter** [comment]
@BeZerkFP, no problem.
https://hastebin.com/ilihokomez.sql
Using in phpmyadmin > SQL or IMPORT

**Comment by BeZerkFP** [comment]
@Heyter Thank you, you are hopefully one of many to get this gamemode completed...pushed the fix.

=== Closing this due to fix being provided ===
